name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Download latest ngrok v3
        run: Invoke-WebRequest https://ngrok-agent.s3.amazonaws.com/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

      - name: Extract ngrok
        run: Expand-Archive ngrok.zip -DestinationPath .

      - name: Authenticate with ngrok
        run: .\ngrok.exe config add-authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Enable Remote Desktop and set password
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
          net user runneradmin P@ssw0rd!

      - name: Start ngrok tunnel to RDP
        run: Start-Process .\ngrok.exe -ArgumentList "tcp 3389"

      - name: Wait for ngrok and show tunnel info
        run: |
          Start-Sleep -Seconds 15
          $response = Invoke-WebRequest -Uri http://127.0.0.1:4040/api/tunnels
          $json = $response.Content | ConvertFrom-Json
          $json.tunnels[0].public_url
